9.4 Efficient numberical method for a regularized least-squares problem

minimize $\Vert Ax-b\Vert_2^2+\delta\Vert x_{1:}-x_{:-1}\Vert_2^2+\eta\Vert x\Vert_2^2$

This objective is convex in x. Set the derivative equal to zero.

$(A^TA+\delta\text{tridiag}+\eta)x=A^Tb$, where the tridiag matrix is shown below.

When $A\in\mathbb{R}^{k\times n},k<<n$ The structure can be exploited by Woodbury matrix identity https://en.wikipedia.org/wiki/Woodbury_matrix_identity
$(A + UCV)^{-1} = A^{-1} - A^{-1} U (C^{-1} + VA^{-1}U)^{-1} VA^{-1}$.



In [3]:
import numpy as np

def create_tridiagonal_matrix(n):
    # Create a tridiagonal matrix of size n x n
    matrix = np.zeros((n, n))

    # Set the main diagonal (values: 2)
    np.fill_diagonal(matrix, 2)

    # Set the upper diagonal (values: -1)
    np.fill_diagonal(matrix[1:], -1)

    # Set the lower diagonal (values: -1)
    np.fill_diagonal(matrix[:, 1:], -1)

    matrix[0,0] = 1
    matrix[-1,-1] = 1

    return matrix

# Specify the size of the tridiagonal matrix (number of rows and columns)
n = 5

# Create the tridiagonal matrix
tridiagonal_matrix = create_tridiagonal_matrix(n)

print(tridiagonal_matrix)


[[ 1. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  1.]]
